---

postgresql_repo_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

postgresql_repo_uris: "http://apt.postgresql.org/pub/repos/apt"
postgresql_repo_suites: "{{ ansible_distribution_release }}-pgdg"
