---
# tasks file for openssh_server debian based distros

- name: "Repository | Ensure prerequisites for PostreSQL Repo"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
  become: true

- name: "Repository | Add PGDG APT repository"
  ansible.builtin.deb822_repository:
    name: "pgdg"
    types: "deb"
    suites: "{{ postgresql_repo_suites }}"
    uris: "{{ postgresql_repo_uris }}"
    components: "main"
    signed_by: "{{ postgresql_repo_key_url }}"
    state: present
    enabled: true
  become: true
