---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
    set -e
    yamllint .
    ansible-lint .
    flake8
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-debian:latest}
    systemd: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: false
    pre_build_image: ${MOLECULE_PRE_BUILD_IMAGE:-true}
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
verifier:
  name: testinfra
